# Generated by Django 6.0 on 2026-01-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
